Repository Tech4covid19/trackovid-landing-page, pull requests merged in 2020-03, with the labels that each got.

#1 Initial commit
  .editorconfig
  .eslintrc.json
  .gitignore
  .huskyrc.json
  .npmrc
  .prettierrc
  .stylelintrc.json
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  gatsby-browser.js
  gatsby-config.js
  jsconfig.json
  lint-staged.config.js
  package.json
  postcss.config.js
  src/assets/.gitkeep
  src/components/header/index.jsx
  src/components/header/index.module.css
  src/components/layout/index.jsx
  src/components/layout/index.module.css
  src/components/seo/index.jsx
  src/pages/404.jsx
  src/pages/index.jsx
  src/sections/hero/index.jsx
  src/sections/hero/index.module.css
  src/styles/all.css
  src/styles/breakpoints.css
  src/styles/reset.css
  yarn.lock
Labels: Status: Ready To Review, Type: Feature

#10 Deploy master to GitHub Pages
  .github/workflows/deploy.yml
  gatsby-config.js
Labels: Status: Ready To Review, Type: Feature

#11 Add Typography component
  src/components/typography/index.jsx
  src/components/typography/index.module.css
  src/sections/hero/index.jsx
  src/styles/all.css
  src/styles/colors.css
  src/styles/variables.css
Labels: Status: Ready To Review, Type: Feature

#12 Footer Component
  .vscode/settings.json
  src/assets/heart.svg
  src/components/footer/index.jsx
  src/components/footer/index.module.css
  src/components/header/index.module.css
  src/components/layout/index.module.css
  src/components/typography/index.jsx
  src/components/typography/index.module.css
  src/pages/index.jsx
  src/sections/hero/index.module.css
  src/styles/all.css
  src/styles/all.module.css
  src/styles/breakpoints.module.css
  src/styles/colors.css
  src/styles/colors.module.css
  src/styles/variables.module.css
Labels: Status: Ready To Review, Type: Feature

#13 Add button component
  gatsby-config.js
  src/components/button/index.jsx
  src/components/button/index.module.css
  src/components/header/index.jsx
  src/components/typography/index.module.css
  src/sections/hero/index.jsx
  src/styles/colors.module.css
  src/styles/variables.module.css
Labels: Status: Ready To Review, Type: Feature

#14 Add "Para Que Serve" section
  src/assets/img-para-que-serve.svg
  src/components/typography/index.jsx
  src/components/typography/index.module.css
  src/pages/index.jsx
  src/sections/para-que-serve/index.jsx
  src/sections/para-que-serve/index.module.css
  src/styles/breakpoints.module.css
  src/styles/colors.module.css
  src/styles/variables.module.css
Labels: Status: Ready To Review, Type: Feature

#16 Update navbar component
  src/components/button/index.module.css
  src/components/header/index.jsx
  src/components/header/index.module.css
  src/components/typography/index.jsx
  src/pages/index.jsx
  src/sections/para-que-serve/index.jsx
  src/styles/main.module.css
Labels: Status: Ready To Review, Type: Feature

#20 Update links and copy
  .eslintrc.json
  gatsby-config.js
  src/assets/hero-app-image.png
  src/assets/hero-image.png
  src/components/button/index.jsx
  src/components/seo/index.jsx
  src/sections/como-usar/index.jsx
  src/sections/hero/index.jsx
  src/sections/para-que-serve/index.jsx
Labels: Status: Ready To Review, Type: Chore

#25 Upgrade dependencies
  .stylelintrc.json
  package.json
  src/styles/variables.module.css
  yarn.lock
Labels: Status: Ready To Review, Type: Chore

#23 Footer, header, and SEO design review
  gatsby-config.js
  src/assets/como-usar1.png
  src/assets/como-usar1.svg
  src/assets/como-usar2.png
  src/assets/como-usar2.svg
  src/assets/como-usar3.png
  src/assets/como-usar3.svg
  src/assets/email.svg
  src/assets/tech4covid19-logo.svg
  src/components/footer/index.jsx
  src/components/footer/index.module.css
  src/components/header/index.module.css
  src/components/logo/index.jsx
  src/components/seo/index.jsx
  src/sections/como-usar/index.jsx
  src/sections/como-usar/index.module.css
  src/sections/hero/index.jsx
  src/sections/hero/index.module.css
  static/favicon.ico
  static/favicon.png
  static/images/logo.png
Labels: Status: Ready To Review, Type: Chore

#22 "Para que serve" section design review
  src/sections/como-usar/index.module.css
  src/sections/para-que-serve/index.jsx
  src/sections/para-que-serve/index.module.css
Labels: Status: Ready To Review, Type: Chore

#28 Improve same domain link check logic
  src/components/button/index.jsx
Labels: Status: Ready To Review, Type: Hotfix

#30 Add GTM and update terms & conditions link
  gatsby-config.js
  package.json
  src/sections/para-que-serve/index.jsx
  yarn.lock
Labels: Status: Ready To Review, Type: Feature

#32 Update header scroll initial state
  src/components/header/index.jsx
Labels: Status: Ready To Review, Type: Hotfix

#35 Fix initial scroll value on hook
  src/components/header/index.jsx
  src/sections/hero/index.module.css
Labels: Status: Ready To Review, Type: Hotfix

#42 [frontend][landing] Update copy of landing page
  gatsby-config.js
  src/components/seo/index.jsx
  src/sections/como-usar/index.jsx
  src/sections/hero/index.jsx
  src/sections/para-que-serve/index.jsx
  static/images/covidografia-share.png
Labels: Status: Ready To Review, Type: Chore
